### PR TITLE
Fix svcomp iterative approach

### PR DESCRIPTION
**Pull request by hernanponcedeleon**

### CODE REVIEW

**Comment by ThomasHaas** [comment]
Is this PR meant to only change the output string? I don't see how this is related to SVCOMP

**Comment by hernanponcedeleon** [comment]
The code iterates over the console lines to find the verification output (one line before the changed code in this PR) and then it uses this to decide if the iterative approach should continue by incrementing the bound or not.

**Comment by ThomasHaas** [comment]
Ok I see. Checking against details of the output like the `(ms)` part sounds not so clever to me :P

**Review by ThomasHaas — APPROVED** [review]
LGTM

**Pull request merged**
