### PR TITLE
Perform loop normalization also on litmus code

### PR DESCRIPTION
**Pull request by ThomasHaas**

### CODE REVIEW

**Comment by ThomasHaas** [comment]
This PR seems to not be needed for now.

**Comment by hernanponcedeleon** [comment]
@ThomasHaas can you also enable any other pass that is needed for #731 ?

**Comment by ThomasHaas** [comment]
There are some tests that none of our passes handle, for example:
```
4:    LC00:
5:       bv64 r0 := rmw[](bv64(1), &Mem0)
6:       if(bv64 r0 != bv64(1)); then goto LC01
7:       goto LC02
8:    LC01:
9:       bv64 r1 := rmw[](bv64(0), &Mem0)
10:      if(bv64 r1 != bv64(1)); then goto LC02
11:      goto LC00
12:   LC02:
13:      bv64 r2 := rmw[](bv64(0), &Mem0)
14:      if(bv64 r2 != bv64(1)); then goto LC03
15:      goto LC01
```
This code has overlapping loops. Here an improved `BranchReordering` might be able swap the last two blocks to get a proper loop.

**Comment by hernanponcedeleon** [comment]
We can keep them in the skip file for now. If we enable loop normalization, the remaining test all have the pattern from your msg above.

If no, I think we can already merge this PR.

**Comment by hernanponcedeleon** [comment]
@ThomasHaas should I merge?

**Comment by ThomasHaas** [comment]
This trivial change can also be included in #731. That one just fails because we need to exclude a bunch more tests.

**Comment by hernanponcedeleon** [comment]
Ok, I cherry-picked your commit to that branch. Closing.

**Pull request closed without merging**
