### PR TITLE
Add support for i8 and i16 types in atomic-replace LLVM pass

### PR DESCRIPTION
**Pull request by idziaszek**

### CODE REVIEW

**Comment by hernanponcedeleon** [comment]
@ThomasHaas can you test this in some of the examples that was causing problems to your students?

**Comment by ThomasHaas** [comment]
I don't have a particular code right now, but I think any code that uses `atomic_bool` should exhibit the problem (for example, simple message passing).
I can try it later.

**Comment by ThomasHaas** [comment]
The code that fails in the current version is:
```c
#include <pthread.h>
#include <stdatomic.h>

atomic_bool flag;
atomic_int data;

void *producer(void *arg)
{
    data = 42;
    flag = 1;
}

void *consumer(void *arg)
{
    while (flag != 1) ;
    assert(data == 42);
}

int main()
{
    atomic_init(&flag, 0);
    pthread_t producer_t, consumer_t;
    pthread_create(&producer_t, NULL, producer, NULL);
    pthread_create(&consumer_t, NULL, consumer, NULL);
}
```
I have trouble installing `atomic-replace` right now, so I cannot test it myself.

**Comment by hernanponcedeleon** [comment]
All good with the pass, now on our side we need to extend our parser
```
[22.06.2023] 19:02:28 [INFO] VisitorBoogie.visitLine_comment - SMACK version: 2.8.0 
Exception in thread "main" com.dat3m.dartagnan.exception.ParsingException: __llvm_atomic8_store cannot be handled
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitProc_decl(VisitorBoogie.java:276)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitCall_cmd(VisitorBoogie.java:399)
        at com.dat3m.dartagnan.parsers.BoogieParser$Call_cmdContext.accept(BoogieParser.java:2752)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.dat3m.dartagnan.parsers.BoogieBaseVisitor.visitLabel_or_cmd(BoogieBaseVisitor.java:177)
        at com.dat3m.dartagnan.parsers.BoogieParser$Label_or_cmdContext.accept(BoogieParser.java:2129)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitProc_decl(VisitorBoogie.java:301)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitMain(VisitorBoogie.java:153)
        at com.dat3m.dartagnan.parsers.BoogieParser$MainContext.accept(BoogieParser.java:235)
        at com.dat3m.dartagnan.parsers.program.ParserBoogie.parse(ParserBoogie.java:26)
        at com.dat3m.dartagnan.parsers.program.ProgramParser.parse(ProgramParser.java:39)
        at com.dat3m.dartagnan.parsers.program.ProgramParser.parse(ProgramParser.java:32)
        at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:105)
```
Thanks @idziaszek foe the update

**Pull request merged**
