### PR TITLE
Upgrade to Java 17

### PR DESCRIPTION
**Pull request by ThomasHaas**
@hernanponcedeleon can you check if this branch works on your side?

### CODE REVIEW

**Comment by ThomasHaas** [comment]
@hernanponcedeleon can you update the `.github/workflows/maven.yml` to use Java 16?
It seems I don't have the rights to change it (my pushes are getting rejected).

**Comment by hernanponcedeleon** [comment]
I updated my java version to 17 and this branch works

**Comment by hernanponcedeleon** [comment]
@xeren can you please check that it also works on your side?

**Comment by hernanponcedeleon** [comment]
We also need to update the docker container

**Comment by ThomasHaas** [comment]
We should probably upgrade to Java 17, cause that is the current LTS version.
I just used Java 16 for testing cause it was the one I had installed on my old Mac :).

**Comment by xeren** [comment]
> @xeren can you please check that it also works on your side?

It works on all of my machines without problems.

**Comment by ThomasHaas** [comment]
This PR will likely not get merged directly and instead come together with the rework.

**Comment by hernanponcedeleon** [comment]
Agree. Closing.

**Pull request closed without merging**
