### PR TITLE
Package restructuring

### PR DESCRIPTION
**Pull request by ThomasHaas**
This PR has not semantics changes at all. It only changes the package-structure of the project:
- The `filter`-package got moved to `program` (it has more to do with program/events than it has to do with wmms).
- Various packages like `atomic` and `svcomp` were merged into the `event`-package.
- The `event`-package is subdivided into 3 packages `core`, `arch` and `lang` with the intention that `core` contains all events that make up our internal language (~LISA), `arch` contains all hardware-specific events (currently `tso` and `aarch64`) and `lang` contains all language specific events (`svcomp`, `catomics`, `pthread` and also `linux`).
- The non-`core` events should all be events that need to be compiled into our core language. Unfortunately, `linux` contains some non-compilable events that are not modelled in `core`. We need to address issue #200 and either get rid of those events or make them part of `core`.

### CODE REVIEW

**Comment by ThomasHaas** [comment]
We have various `utils` packages with single classes in `arch` and `lang`. What do you guys think of moving these classes into the parent package and removing all these `utils` to reduce the nesting of package?

**Comment by xeren** [comment]
I support the flattening of the package structure, except `com.dat3m.dartagnan.utils`.  It allows more usage of package-private accessible members.

**Comment by ThomasHaas** [comment]
I wouldn't want to flatten the top-level `utils` package. I'm talking more about all these small `utils`-packages that contain a single `EType` or `Mo` class and possibly also the one that contains `EventCache` (renamed from `ThreadCache)`. 

Also, we should probably streamline the naming scheme of `Mo` and `EType`. I think `Mo` is essentially a subset of `EType`, concerned with the tags of memory operations. I would also rename `EType` to `ETag` or just `Tag`, because the word "type" suggests a distinction between something like Load, Store and Fence but we use it for all kinds of attached information, e.g. visibility, mo and strongness.

**Comment by hernanponcedeleon** [comment]
I fully agree in flattening the `.utils` in event packages (also the one containing `EventCache`).

I think originally there was more of a distinction between these classes: while `Mo` was (and still is) about memory ordering, we did so many modifications to `EType` that I'm not even sure we have a "unified use" for them. Since at the end of all of them are tags (and all their uses match the use of tags in cat), I propose to create a tag package with maybe some further sub-packages like `mo`, `arch`, etc.

**Pull request merged**
